name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Enable manual run from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
        with:
          # Checkout pull request HEAD commit instead of merge commit
          # Codecov checks do not get reported unless this ref is checked out
          ref: ${{ github.event.pull_request.head.sha }}
      - run: go build ./...
      - run: go test ./... -covermode=atomic -coverprofile=coverage.out -coverpkg=./... -count=1 -race
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
          files: ./coverage.out
          fail_ci_if_error: true
          verbose: false
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
