name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Installs and configures Go
      - name: go setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
    
      # Checks-out your repo under $GITHUB_WORKSPACE
      - name: checkout
        uses: actions/checkout@v3

      # Builds code
      - name: build
        run: go build ./...

      # Tests code
      - name: test
        run: go test ./... -covermode=atomic -coverprofile=coverage.out -coverpkg=./... -count=1 -race

      # Uploads test report to codecov
      - name: coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
          files: ./coverage.out
          fail_ci_if_error: true
          verbose: false

      # Runs golangci-lint
      - name: lint
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: latest
