name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Enable manual run from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go build ./...
      - run: go test ./... -covermode=atomic -coverprofile=coverage.out -coverpkg=./... -count=1 -race
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out
          fail_ci_if_error: true
          verbose: false
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
